/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.UIManager;

/**
 *
 * @author Administrador
 */
public class Vbasica extends javax.swing.JFrame {

  /**
   * Creates new form Vbasica
   */
  
  
  public Vbasica() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel3 = new javax.swing.JPanel();
    btn_sin = new javax.swing.JButton();
    btn_cos = new javax.swing.JButton();
    btn_tan = new javax.swing.JButton();
    btn_log = new javax.swing.JButton();
    btn_raiz = new javax.swing.JButton();
    btn_asin = new javax.swing.JButton();
    btn_acos = new javax.swing.JButton();
    btn_atan = new javax.swing.JButton();
    btn_ln = new javax.swing.JButton();
    btn_pot = new javax.swing.JButton();
    btn_siete = new javax.swing.JButton();
    btn_ocho = new javax.swing.JButton();
    btn_nueve = new javax.swing.JButton();
    btn_parenIzq = new javax.swing.JButton();
    btn_parenDer = new javax.swing.JButton();
    btn_cuatro = new javax.swing.JButton();
    btn_cinco = new javax.swing.JButton();
    btn_seis = new javax.swing.JButton();
    btn_multiplicar = new javax.swing.JButton();
    btn_division = new javax.swing.JButton();
    btn_dos = new javax.swing.JButton();
    btn_tres = new javax.swing.JButton();
    btn_uno = new javax.swing.JButton();
    btn_igual = new javax.swing.JButton();
    btn_clear = new javax.swing.JButton();
    btn_exponente = new javax.swing.JButton();
    btn_punto = new javax.swing.JButton();
    btn_cero = new javax.swing.JButton();
    btn_suma = new javax.swing.JButton();
    btn_resta = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    txt_anuncio = new javax.swing.JTextField();
    txt_fix = new javax.swing.JTextField();
    btn_memoria = new javax.swing.JButton();
    btn_listaMemoria = new javax.swing.JButton();
    btn_file = new javax.swing.JButton();
    btn_fix = new javax.swing.JButton();
    txt_resultado = new javax.swing.JTextField();
    mbar = new javax.swing.JMenuBar();
    m_vistas = new javax.swing.JMenu();
    item_booleana = new javax.swing.JMenuItem();
    item_estadistica = new javax.swing.JMenuItem();
    item_compl = new javax.swing.JMenuItem();
    item_salir = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Calculadora Basica");
    setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
    setResizable(false);

    btn_sin.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_sin.setForeground(java.awt.Color.darkGray);
    btn_sin.setText("SIN");
    btn_sin.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_sin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_sinActionPerformed(evt);
      }
    });

    btn_cos.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_cos.setForeground(java.awt.Color.darkGray);
    btn_cos.setText("COS");
    btn_cos.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_cos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_cosActionPerformed(evt);
      }
    });

    btn_tan.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_tan.setForeground(java.awt.Color.darkGray);
    btn_tan.setText("TAN");
    btn_tan.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_tan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_tanActionPerformed(evt);
      }
    });

    btn_log.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_log.setForeground(java.awt.Color.darkGray);
    btn_log.setText("LOG");
    btn_log.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_log.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_logActionPerformed(evt);
      }
    });

    btn_raiz.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_raiz.setForeground(java.awt.Color.darkGray);
    btn_raiz.setText("√");
    btn_raiz.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_raiz.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_raizActionPerformed(evt);
      }
    });

    btn_asin.setFont(new java.awt.Font("Monospaced", 1, 11));
    btn_asin.setForeground(java.awt.Color.darkGray);
    btn_asin.setText("ASIN");
    btn_asin.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_asin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_asinActionPerformed(evt);
      }
    });

    btn_acos.setFont(new java.awt.Font("Monospaced", 1, 11));
    btn_acos.setForeground(java.awt.Color.darkGray);
    btn_acos.setText("ACOS");
    btn_acos.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_acos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_acosActionPerformed(evt);
      }
    });

    btn_atan.setFont(new java.awt.Font("Monospaced", 1, 11));
    btn_atan.setForeground(java.awt.Color.darkGray);
    btn_atan.setText("ATAN");
    btn_atan.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_atan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_atanActionPerformed(evt);
      }
    });

    btn_ln.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_ln.setForeground(java.awt.Color.darkGray);
    btn_ln.setText("LN");
    btn_ln.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_ln.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_lnActionPerformed(evt);
      }
    });

    btn_pot.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_pot.setForeground(java.awt.Color.darkGray);
    btn_pot.setText("^");
    btn_pot.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_pot.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_potActionPerformed(evt);
      }
    });

    btn_siete.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_siete.setForeground(java.awt.Color.darkGray);
    btn_siete.setText("7");
    btn_siete.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_siete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_sieteActionPerformed(evt);
      }
    });

    btn_ocho.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_ocho.setForeground(java.awt.Color.darkGray);
    btn_ocho.setText("8");
    btn_ocho.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_ocho.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ochoActionPerformed(evt);
      }
    });

    btn_nueve.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_nueve.setForeground(java.awt.Color.darkGray);
    btn_nueve.setText("9");
    btn_nueve.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_nueve.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_nueveActionPerformed(evt);
      }
    });

    btn_parenIzq.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_parenIzq.setForeground(java.awt.Color.darkGray);
    btn_parenIzq.setText("(");
    btn_parenIzq.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_parenIzq.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_parenIzqActionPerformed(evt);
      }
    });

    btn_parenDer.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_parenDer.setForeground(java.awt.Color.darkGray);
    btn_parenDer.setText(")");
    btn_parenDer.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_parenDer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_parenDerActionPerformed(evt);
      }
    });

    btn_cuatro.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_cuatro.setForeground(java.awt.Color.darkGray);
    btn_cuatro.setText("4");
    btn_cuatro.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_cuatro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_cuatroActionPerformed(evt);
      }
    });

    btn_cinco.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_cinco.setForeground(java.awt.Color.darkGray);
    btn_cinco.setText("5");
    btn_cinco.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_cinco.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_cincoActionPerformed(evt);
      }
    });

    btn_seis.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_seis.setForeground(java.awt.Color.darkGray);
    btn_seis.setText("6");
    btn_seis.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_seis.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_seisActionPerformed(evt);
      }
    });

    btn_multiplicar.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_multiplicar.setForeground(java.awt.Color.darkGray);
    btn_multiplicar.setText("*");
    btn_multiplicar.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_multiplicarActionPerformed(evt);
      }
    });

    btn_division.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_division.setForeground(java.awt.Color.darkGray);
    btn_division.setText("/");
    btn_division.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_division.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_divisionActionPerformed(evt);
      }
    });

    btn_dos.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_dos.setForeground(java.awt.Color.darkGray);
    btn_dos.setText("2");
    btn_dos.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_dos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_dosActionPerformed(evt);
      }
    });

    btn_tres.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_tres.setForeground(java.awt.Color.darkGray);
    btn_tres.setText("3");
    btn_tres.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_tres.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_tresActionPerformed(evt);
      }
    });

    btn_uno.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_uno.setForeground(java.awt.Color.darkGray);
    btn_uno.setText("1");
    btn_uno.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_uno.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_unoActionPerformed(evt);
      }
    });

    btn_igual.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_igual.setForeground(java.awt.Color.darkGray);
    btn_igual.setText("=");
    btn_igual.setPreferredSize(new java.awt.Dimension(52, 28));

    btn_clear.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_clear.setForeground(java.awt.Color.darkGray);
    btn_clear.setText("AC");
    btn_clear.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_clear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_clearActionPerformed(evt);
      }
    });

    btn_exponente.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_exponente.setForeground(java.awt.Color.darkGray);
    btn_exponente.setText("E");
    btn_exponente.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_exponente.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_exponenteActionPerformed(evt);
      }
    });

    btn_punto.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_punto.setForeground(java.awt.Color.darkGray);
    btn_punto.setText(".");
    btn_punto.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_punto.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_puntoActionPerformed(evt);
      }
    });

    btn_cero.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_cero.setForeground(java.awt.Color.darkGray);
    btn_cero.setText("0");
    btn_cero.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_cero.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ceroActionPerformed(evt);
      }
    });

    btn_suma.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_suma.setForeground(java.awt.Color.darkGray);
    btn_suma.setText("+");
    btn_suma.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_suma.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_sumaActionPerformed(evt);
      }
    });

    btn_resta.setFont(new java.awt.Font("Monospaced", 1, 12));
    btn_resta.setForeground(java.awt.Color.darkGray);
    btn_resta.setText("-");
    btn_resta.setPreferredSize(new java.awt.Dimension(52, 28));
    btn_resta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_restaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(btn_asin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_acos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_atan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_pot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(btn_sin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_cos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_tan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_raiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(btn_cero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_exponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(btn_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_seis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(btn_uno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_dos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_tres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(btn_siete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_parenIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_parenDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(6, Short.MAX_VALUE))
    );

    jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_acos, btn_asin, btn_atan, btn_cero, btn_cinco, btn_clear, btn_cos, btn_cuatro, btn_division, btn_dos, btn_exponente, btn_igual, btn_ln, btn_log, btn_multiplicar, btn_nueve, btn_ocho, btn_parenDer, btn_parenIzq, btn_pot, btn_punto, btn_raiz, btn_resta, btn_seis, btn_siete, btn_sin, btn_suma, btn_tan, btn_tres, btn_uno});

    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
          .addComponent(btn_sin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_cos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_tan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_raiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
          .addComponent(btn_asin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_acos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_atan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_ln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_pot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
          .addComponent(btn_siete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_parenIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_parenDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
          .addComponent(btn_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_seis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
          .addComponent(btn_uno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_dos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_tres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
          .addComponent(btn_cero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_exponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_acos, btn_asin, btn_atan, btn_cero, btn_cinco, btn_clear, btn_cos, btn_cuatro, btn_division, btn_dos, btn_exponente, btn_igual, btn_ln, btn_log, btn_multiplicar, btn_nueve, btn_ocho, btn_parenDer, btn_parenIzq, btn_pot, btn_punto, btn_raiz, btn_resta, btn_seis, btn_siete, btn_sin, btn_suma, btn_tan, btn_tres, btn_uno});

    txt_anuncio.setEditable(false);
    txt_anuncio.setFont(new java.awt.Font("Monospaced", 1, 22));
    txt_anuncio.setText(" ");
    txt_anuncio.setToolTipText("");
    txt_anuncio.setAlignmentX(0.0F);
    txt_anuncio.setAlignmentY(0.0F);
    txt_anuncio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    txt_fix.setEditable(false);
    txt_fix.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    txt_fix.setPreferredSize(new java.awt.Dimension(50, 30));

    btn_memoria.setText("M");
    btn_memoria.setPreferredSize(new java.awt.Dimension(50, 30));

    btn_listaMemoria.setText("LM");
    btn_listaMemoria.setPreferredSize(new java.awt.Dimension(50, 30));
    btn_listaMemoria.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_listaMemoriaActionPerformed(evt);
      }
    });

    btn_file.setText("FILE");
    btn_file.setPreferredSize(new java.awt.Dimension(50, 30));

    btn_fix.setText("FIX");
    btn_fix.setPreferredSize(new java.awt.Dimension(50, 30));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txt_anuncio, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(btn_memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_listaMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_fix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_fix, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btn_file, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_fix, btn_listaMemoria});

    jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_anuncio, txt_resultado});

    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addComponent(txt_anuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
          .addComponent(txt_fix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_memoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_listaMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_fix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_file, btn_fix, btn_listaMemoria, btn_memoria, txt_fix});

    m_vistas.setText("Vistas");

    item_booleana.setText("Booleana");
    item_booleana.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        item_booleanaActionPerformed(evt);
      }
    });
    m_vistas.add(item_booleana);

    item_estadistica.setText("Estadistica");
    item_estadistica.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        item_estadisticaActionPerformed(evt);
      }
    });
    m_vistas.add(item_estadistica);

    item_compl.setText("Completa");
    m_vistas.add(item_compl);

    item_salir.setText("Salir");
    m_vistas.add(item_salir);

    mbar.add(m_vistas);

    setJMenuBar(mbar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(20, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(38, 38, 38)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(36, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sinActionPerformed
// TODO add your handling code here:
    parseBotones("sin");
  }//GEN-LAST:event_btn_sinActionPerformed

  private void btn_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cosActionPerformed
// TODO add your handling code here:
    parseBotones("cos");
    this.setBackground(java.awt.Color.BLUE);
  }//GEN-LAST:event_btn_cosActionPerformed

  private void btn_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tanActionPerformed
// TODO add your handling code here:
    parseBotones("tan");
  }//GEN-LAST:event_btn_tanActionPerformed

  private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
// TODO add your handling code here:
    parseBotones("log");
  }//GEN-LAST:event_btn_logActionPerformed

  private void btn_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raizActionPerformed
// TODO add your handling code here:
    parseBotones("√");
  }//GEN-LAST:event_btn_raizActionPerformed

  private void btn_asinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asinActionPerformed
// TODO add your handling code here:
    parseBotones("asin");
  }//GEN-LAST:event_btn_asinActionPerformed

  private void btn_acosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acosActionPerformed
// TODO add your handling code here:
    parseBotones("acos");
  }//GEN-LAST:event_btn_acosActionPerformed

  private void btn_atanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atanActionPerformed
// TODO add your handling code here:
    parseBotones("atan");
  }//GEN-LAST:event_btn_atanActionPerformed

  private void btn_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lnActionPerformed
// TODO add your handling code here:
    parseBotones("ln");
  }//GEN-LAST:event_btn_lnActionPerformed

  private void btn_potActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potActionPerformed
// TODO add your handling code here:
    parseBotones("^");
  }//GEN-LAST:event_btn_potActionPerformed

  private void btn_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sieteActionPerformed
// TODO add your handling code here:
    parseBotones("7");
  }//GEN-LAST:event_btn_sieteActionPerformed

  private void btn_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ochoActionPerformed
// TODO add your handling code here:
    parseBotones("8");
  }//GEN-LAST:event_btn_ochoActionPerformed

  private void btn_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueveActionPerformed
// TODO add your handling code here:
    parseBotones("9");
  }//GEN-LAST:event_btn_nueveActionPerformed

  private void btn_parenIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parenIzqActionPerformed
// TODO add your handling code here:
    parseBotones("(");
  }//GEN-LAST:event_btn_parenIzqActionPerformed

  private void btn_parenDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parenDerActionPerformed
// TODO add your handling code here:
    parseBotones(")");
  }//GEN-LAST:event_btn_parenDerActionPerformed

  private void btn_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuatroActionPerformed
// TODO add your handling code here:
    parseBotones("4");
  }//GEN-LAST:event_btn_cuatroActionPerformed

  private void btn_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cincoActionPerformed
// TODO add your handling code here:
    parseBotones("5");
  }//GEN-LAST:event_btn_cincoActionPerformed

  private void btn_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seisActionPerformed
// TODO add your handling code here:
    parseBotones("6");
  }//GEN-LAST:event_btn_seisActionPerformed

  private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
// TODO add your handling code here:
    parseBotones("*");
  }//GEN-LAST:event_btn_multiplicarActionPerformed

  private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
// TODO add your handling code here:
    parseBotones("/");
  }//GEN-LAST:event_btn_divisionActionPerformed

  private void btn_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dosActionPerformed
// TODO add your handling code here:
    parseBotones("2");
  }//GEN-LAST:event_btn_dosActionPerformed

  private void btn_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tresActionPerformed
// TODO add your handling code here:
    parseBotones("3");
  }//GEN-LAST:event_btn_tresActionPerformed

  private void btn_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unoActionPerformed
// TODO add your handling code here:
    parseBotones("1");
  }//GEN-LAST:event_btn_unoActionPerformed

  private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
// TODO add your handling code here:
    txt_resultado.setText("");
  }//GEN-LAST:event_btn_clearActionPerformed

  private void btn_exponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exponenteActionPerformed
// TODO add your handling code here:
    parseBotones("E");
  }//GEN-LAST:event_btn_exponenteActionPerformed

  private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
// TODO add your handling code here:
    parseBotones(".");
  }//GEN-LAST:event_btn_puntoActionPerformed

  private void btn_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceroActionPerformed
// TODO add your handling code here:
    parseBotones("0");
//    txt_resultado.setText(INPUT);
  }//GEN-LAST:event_btn_ceroActionPerformed

  private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
// TODO add your handling code here:
    parseBotones("+");
  }//GEN-LAST:event_btn_sumaActionPerformed

  private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
// TODO add your handling code here:
    parseBotones("-");
  }//GEN-LAST:event_btn_restaActionPerformed

  private void parseBotones(String boton){
    if(txt_resultado.getText().equals("") ){
      txt_resultado.setText(boton);
      String aux=txt_resultado.getText();
      txt_resultado.setText(aux);
    }else{
      String aux=txt_resultado.getText()+boton;
      txt_resultado.setText(aux);
    }
  }
  
  private void item_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_estadisticaActionPerformed
    // TODO add your handling code here:
    
  }//GEN-LAST:event_item_estadisticaActionPerformed

  private void item_booleanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_booleanaActionPerformed
    // TODO add your handling code here:
    
  }//GEN-LAST:event_item_booleanaActionPerformed

  private void btn_listaMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaMemoriaActionPerformed
    // TODO add your handling code here:
//    Dlg_info dlg_info=new Dlg_info(this, rootPaneCheckingEnabled);
//    Controller controller=new Controller(this, null, null);
//    String aux=controller.getMemoriaDialog();
//    dlg_info.txtA_info.setText(aux);
//    dlg_info.setVisible(rootPaneCheckingEnabled);
  }//GEN-LAST:event_btn_listaMemoriaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Vbasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Vbasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Vbasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Vbasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {

      @Override
      public void run() {
        new Vbasica().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_acos;
  private javax.swing.JButton btn_asin;
  private javax.swing.JButton btn_atan;
  private javax.swing.JButton btn_cero;
  private javax.swing.JButton btn_cinco;
  public javax.swing.JButton btn_clear;
  private javax.swing.JButton btn_cos;
  private javax.swing.JButton btn_cuatro;
  public javax.swing.JButton btn_division;
  private javax.swing.JButton btn_dos;
  private javax.swing.JButton btn_exponente;
  public javax.swing.JButton btn_file;
  public javax.swing.JButton btn_fix;
  public javax.swing.JButton btn_igual;
  public javax.swing.JButton btn_listaMemoria;
  private javax.swing.JButton btn_ln;
  private javax.swing.JButton btn_log;
  public javax.swing.JButton btn_memoria;
  private javax.swing.JButton btn_multiplicar;
  private javax.swing.JButton btn_nueve;
  private javax.swing.JButton btn_ocho;
  private javax.swing.JButton btn_parenDer;
  private javax.swing.JButton btn_parenIzq;
  private javax.swing.JButton btn_pot;
  private javax.swing.JButton btn_punto;
  private javax.swing.JButton btn_raiz;
  private javax.swing.JButton btn_resta;
  private javax.swing.JButton btn_seis;
  private javax.swing.JButton btn_siete;
  public javax.swing.JButton btn_sin;
  private javax.swing.JButton btn_suma;
  private javax.swing.JButton btn_tan;
  private javax.swing.JButton btn_tres;
  private javax.swing.JButton btn_uno;
  public javax.swing.JMenuItem item_booleana;
  public javax.swing.JMenuItem item_compl;
  public javax.swing.JMenuItem item_estadistica;
  public javax.swing.JMenuItem item_salir;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  public javax.swing.JMenu m_vistas;
  private javax.swing.JMenuBar mbar;
  public javax.swing.JTextField txt_anuncio;
  public javax.swing.JTextField txt_fix;
  public javax.swing.JTextField txt_resultado;
  // End of variables declaration//GEN-END:variables
}
