/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Vbooleana.java
 *
 * Created on 29-jun-2012, 14:47:23
 */
package vista;

/**
 *
 * @author samuel

 */
public class Vbooleana extends javax.swing.JFrame {

    /** Creates new form Vbooleana */
   
    public Vbooleana() {
        initComponents();
        btnG_boolean1.add(rbtn_decimal) ;
        btnG_boolean1.add(rbtn_binario);
        btnG_boolean1.add(rbtn_octal);
        btnG_boolean1.add(rbtn_hexad);
        btnG_boolean2.add(rbtn_decimal1);
        btnG_boolean2.add(rbtn_binario1);
        btnG_boolean2.add(rbtn_octal1);
        btnG_boolean2.add(rbtn_hexad1);
        btnG_hub.add(chb_conversiones);
        btnG_hub.add(chb_operaciones);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnG_boolean1 = new javax.swing.ButtonGroup();
    btnG_boolean2 = new javax.swing.ButtonGroup();
    btnG_hub = new javax.swing.ButtonGroup();
    pn_booleno = new javax.swing.JPanel();
    txt_result = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    btn_A = new javax.swing.JButton();
    btn_C = new javax.swing.JButton();
    btn_E = new javax.swing.JButton();
    btn_7 = new javax.swing.JButton();
    btn_8 = new javax.swing.JButton();
    btn_9 = new javax.swing.JButton();
    btn_B = new javax.swing.JButton();
    btn_4 = new javax.swing.JButton();
    btn_5 = new javax.swing.JButton();
    btn_6 = new javax.swing.JButton();
    btn_1 = new javax.swing.JButton();
    btn_2 = new javax.swing.JButton();
    btn_D = new javax.swing.JButton();
    btn_clear = new javax.swing.JButton();
    btn_F = new javax.swing.JButton();
    btn_3 = new javax.swing.JButton();
    btn_igual = new javax.swing.JButton();
    btn_clear1 = new javax.swing.JButton();
    btn_punto = new javax.swing.JButton();
    btn_0 = new javax.swing.JButton();
    btn_producto = new javax.swing.JButton();
    btn_suma = new javax.swing.JButton();
    btn_division = new javax.swing.JButton();
    btn_resta = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    rbtn_decimal = new javax.swing.JRadioButton();
    rbtn_binario = new javax.swing.JRadioButton();
    rbtn_octal = new javax.swing.JRadioButton();
    rbtn_hexad = new javax.swing.JRadioButton();
    jPanel5 = new javax.swing.JPanel();
    rbtn_decimal1 = new javax.swing.JRadioButton();
    rbtn_binario1 = new javax.swing.JRadioButton();
    rbtn_octal1 = new javax.swing.JRadioButton();
    rbtn_hexad1 = new javax.swing.JRadioButton();
    chb_operaciones = new javax.swing.JCheckBox();
    chb_conversiones = new javax.swing.JCheckBox();
    mbar = new javax.swing.JMenuBar();
    m_vistas = new javax.swing.JMenu();
    item_basica = new javax.swing.JMenuItem();
    item_estadistica = new javax.swing.JMenuItem();
    item_salir = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    pn_booleno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booleanos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Unicode MS", 1, 14), java.awt.Color.darkGray)); // NOI18N

    btn_A.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_A.setForeground(java.awt.Color.darkGray);
    btn_A.setText("A");
    btn_A.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_A.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_AActionPerformed(evt);
      }
    });

    btn_C.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_C.setForeground(java.awt.Color.darkGray);
    btn_C.setText("C");
    btn_C.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_C.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_CActionPerformed(evt);
      }
    });

    btn_E.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
    btn_E.setForeground(java.awt.Color.darkGray);
    btn_E.setText("E");
    btn_E.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_E.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_EActionPerformed(evt);
      }
    });

    btn_7.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_7.setForeground(java.awt.Color.darkGray);
    btn_7.setText("7");
    btn_7.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_7ActionPerformed(evt);
      }
    });

    btn_8.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_8.setForeground(java.awt.Color.darkGray);
    btn_8.setText("8");
    btn_8.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_8ActionPerformed(evt);
      }
    });

    btn_9.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_9.setForeground(java.awt.Color.darkGray);
    btn_9.setText("9");
    btn_9.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_9ActionPerformed(evt);
      }
    });

    btn_B.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_B.setForeground(java.awt.Color.darkGray);
    btn_B.setText("B");
    btn_B.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_B.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_BActionPerformed(evt);
      }
    });

    btn_4.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_4.setForeground(java.awt.Color.darkGray);
    btn_4.setText("4");
    btn_4.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_4ActionPerformed(evt);
      }
    });

    btn_5.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_5.setForeground(java.awt.Color.darkGray);
    btn_5.setText("5");
    btn_5.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_5ActionPerformed(evt);
      }
    });

    btn_6.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_6.setForeground(java.awt.Color.darkGray);
    btn_6.setText("6");
    btn_6.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_6ActionPerformed(evt);
      }
    });

    btn_1.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_1.setForeground(java.awt.Color.darkGray);
    btn_1.setText("1");
    btn_1.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_1ActionPerformed(evt);
      }
    });

    btn_2.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_2.setForeground(java.awt.Color.darkGray);
    btn_2.setText("2");
    btn_2.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_2ActionPerformed(evt);
      }
    });

    btn_D.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_D.setForeground(java.awt.Color.darkGray);
    btn_D.setText("D");
    btn_D.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_D.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_DActionPerformed(evt);
      }
    });

    btn_clear.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_clear.setForeground(java.awt.Color.darkGray);
    btn_clear.setText("AC");
    btn_clear.setPreferredSize(new java.awt.Dimension(44, 28));
    btn_clear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_clearActionPerformed(evt);
      }
    });

    btn_F.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_F.setForeground(java.awt.Color.darkGray);
    btn_F.setText("F");
    btn_F.setPreferredSize(new java.awt.Dimension(44, 28));
    btn_F.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_FActionPerformed(evt);
      }
    });

    btn_3.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_3.setForeground(java.awt.Color.darkGray);
    btn_3.setText("3");
    btn_3.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_3ActionPerformed(evt);
      }
    });

    btn_igual.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_igual.setForeground(java.awt.Color.darkGray);
    btn_igual.setText("=");
    btn_igual.setPreferredSize(new java.awt.Dimension(44, 28));

    btn_clear1.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_clear1.setForeground(java.awt.Color.darkGray);
    btn_clear1.setText("<");
    btn_clear1.setPreferredSize(new java.awt.Dimension(44, 28));
    btn_clear1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_clear1ActionPerformed(evt);
      }
    });

    btn_punto.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
    btn_punto.setForeground(java.awt.Color.darkGray);
    btn_punto.setText(".");
    btn_punto.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_punto.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_puntoActionPerformed(evt);
      }
    });

    btn_0.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_0.setForeground(java.awt.Color.darkGray);
    btn_0.setText("0");
    btn_0.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_0.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_0ActionPerformed(evt);
      }
    });

    btn_producto.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_producto.setForeground(java.awt.Color.darkGray);
    btn_producto.setText("*");
    btn_producto.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_producto.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_productoActionPerformed(evt);
      }
    });

    btn_suma.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_suma.setForeground(java.awt.Color.darkGray);
    btn_suma.setText("+");
    btn_suma.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_suma.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_sumaActionPerformed(evt);
      }
    });

    btn_division.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_division.setForeground(java.awt.Color.darkGray);
    btn_division.setText("/");
    btn_division.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_division.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_divisionActionPerformed(evt);
      }
    });

    btn_resta.setFont(new java.awt.Font("Monospaced", 1, 13));
    btn_resta.setForeground(java.awt.Color.darkGray);
    btn_resta.setText("-");
    btn_resta.setPreferredSize(new java.awt.Dimension(42, 28));
    btn_resta.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_restaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(btn_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(btn_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );

    jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_F, btn_clear, btn_clear1, btn_igual});

    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
          .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_clear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    rbtn_decimal.setSelected(true);
    rbtn_decimal.setText("decimal");

    rbtn_binario.setText("binario");

    rbtn_octal.setText("octal");

    rbtn_hexad.setText("hexadecimal");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(rbtn_decimal)
          .addComponent(rbtn_binario)
          .addComponent(rbtn_octal)
          .addComponent(rbtn_hexad))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addComponent(rbtn_decimal)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbtn_binario)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbtn_octal)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbtn_hexad))
    );

    rbtn_decimal1.setSelected(true);
    rbtn_decimal1.setText("decimal");

    rbtn_binario1.setText("binario");

    rbtn_octal1.setText("octal");

    rbtn_hexad1.setText("hexadecimal");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(rbtn_decimal1)
      .addComponent(rbtn_binario1)
      .addComponent(rbtn_octal1)
      .addComponent(rbtn_hexad1)
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addComponent(rbtn_decimal1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbtn_binario1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbtn_octal1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(rbtn_hexad1))
    );

    chb_operaciones.setText("Operaciones");

    chb_conversiones.setSelected(true);
    chb_conversiones.setText("Conversiones");

    javax.swing.GroupLayout pn_boolenoLayout = new javax.swing.GroupLayout(pn_booleno);
    pn_booleno.setLayout(pn_boolenoLayout);
    pn_boolenoLayout.setHorizontalGroup(
      pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_boolenoLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_boolenoLayout.createSequentialGroup()
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pn_boolenoLayout.createSequentialGroup()
              .addComponent(chb_conversiones)
              .addGap(36, 36, 36)
              .addComponent(chb_operaciones))
            .addComponent(txt_result, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(69, 69, 69))
      .addGroup(pn_boolenoLayout.createSequentialGroup()
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    pn_boolenoLayout.setVerticalGroup(
      pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_boolenoLayout.createSequentialGroup()
        .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(chb_conversiones)
          .addComponent(chb_operaciones))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txt_result, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(58, 58, 58))
    );

    m_vistas.setText("Vistas");

    item_basica.setText("Basica");
    item_basica.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        item_basicaActionPerformed(evt);
      }
    });
    m_vistas.add(item_basica);

    item_estadistica.setText("Estadistica");
    item_estadistica.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        item_estadisticaActionPerformed(evt);
      }
    });
    m_vistas.add(item_estadistica);

    item_salir.setText("Salir");
    m_vistas.add(item_salir);

    mbar.add(m_vistas);

    setJMenuBar(mbar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(pn_booleno, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(pn_booleno, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void item_basicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_basicaActionPerformed
    // TODO add your handling code here:
    
  }//GEN-LAST:event_item_basicaActionPerformed

  private void item_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_estadisticaActionPerformed
    // TODO add your handling code here:
    /*if (vBol == false) {
      vbol.setVisible(true);
      this.setVisible(false);
      vBol = true;
    } else {
      vbol.setVisible(false);
      this.setVisible(true);
      vBol = false;
    }*/
  }//GEN-LAST:event_item_estadisticaActionPerformed

private void btn_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AActionPerformed
// TODO add your handling code here:
    parseBotones("A");
}//GEN-LAST:event_btn_AActionPerformed

private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
// TODO add your handling code here:
    parseBotones("C");
}//GEN-LAST:event_btn_CActionPerformed

private void btn_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EActionPerformed
// TODO add your handling code here:
    parseBotones("E");
}//GEN-LAST:event_btn_EActionPerformed

private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
// TODO add your handling code here:
    parseBotones("7");
}//GEN-LAST:event_btn_7ActionPerformed

private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
// TODO add your handling code here:
    parseBotones("8");
}//GEN-LAST:event_btn_8ActionPerformed

private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
// TODO add your handling code here:
    parseBotones("9");
}//GEN-LAST:event_btn_9ActionPerformed

private void btn_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BActionPerformed
// TODO add your handling code here:
    parseBotones("B");
}//GEN-LAST:event_btn_BActionPerformed

private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
// TODO add your handling code here:
    parseBotones("4");
}//GEN-LAST:event_btn_4ActionPerformed

private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
// TODO add your handling code here:
    parseBotones("5");
}//GEN-LAST:event_btn_5ActionPerformed

private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
// TODO add your handling code here:
    parseBotones("6");
}//GEN-LAST:event_btn_6ActionPerformed

private void btn_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productoActionPerformed
// TODO add your handling code here:
    parseBotones("*");
}//GEN-LAST:event_btn_productoActionPerformed

private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
// TODO add your handling code here:
    parseBotones("1");
}//GEN-LAST:event_btn_1ActionPerformed

private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
// TODO add your handling code here:
    parseBotones("2");
}//GEN-LAST:event_btn_2ActionPerformed

private void btn_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DActionPerformed
// TODO add your handling code here:
    parseBotones("D");
}//GEN-LAST:event_btn_DActionPerformed

private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
// TODO add your handling code here:
    parseBotones("0");
}//GEN-LAST:event_btn_0ActionPerformed

private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
// TODO add your handling code here:
    txt_result.setText("");
}//GEN-LAST:event_btn_clearActionPerformed

private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
// TODO add your handling code here:
    parseBotones(".");
}//GEN-LAST:event_btn_puntoActionPerformed

private void btn_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FActionPerformed
// TODO add your handling code here:
    parseBotones("F");
//    txt_resultado.setText(INPUT);
}//GEN-LAST:event_btn_FActionPerformed

private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
// TODO add your handling code here:
    parseBotones("3");
}//GEN-LAST:event_btn_3ActionPerformed

private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
// TODO add your handling code here:
    parseBotones("+");
}//GEN-LAST:event_btn_sumaActionPerformed

private void btn_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear1ActionPerformed
// TODO add your handling code here:
  String aux=txt_result.getText().substring(0,txt_result.getText().length()-1);
  txt_result.setText(aux);
}//GEN-LAST:event_btn_clear1ActionPerformed

private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
// TODO add your handling code here:
  parseBotones("/");
}//GEN-LAST:event_btn_divisionActionPerformed

private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
// TODO add your handling code here:
  parseBotones("-");
}//GEN-LAST:event_btn_restaActionPerformed

private void parseBotones(String boton){
    if(txt_result.getText().equals("") ){
      txt_result.setText(boton);
      String aux=txt_result.getText();
      txt_result.setText(aux);
    }else{
      String aux=txt_result.getText()+boton;
      txt_result.setText(aux);
    }
  }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vbooleana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vbooleana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vbooleana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vbooleana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

      @Override
            public void run() {
                new Vbooleana().setVisible(true);
            }
        });
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.ButtonGroup btnG_boolean1;
  public javax.swing.ButtonGroup btnG_boolean2;
  public javax.swing.ButtonGroup btnG_hub;
  private javax.swing.JButton btn_0;
  private javax.swing.JButton btn_1;
  private javax.swing.JButton btn_2;
  private javax.swing.JButton btn_3;
  private javax.swing.JButton btn_4;
  private javax.swing.JButton btn_5;
  private javax.swing.JButton btn_6;
  private javax.swing.JButton btn_7;
  private javax.swing.JButton btn_8;
  private javax.swing.JButton btn_9;
  private javax.swing.JButton btn_A;
  private javax.swing.JButton btn_B;
  private javax.swing.JButton btn_C;
  private javax.swing.JButton btn_D;
  private javax.swing.JButton btn_E;
  private javax.swing.JButton btn_F;
  private javax.swing.JButton btn_clear;
  private javax.swing.JButton btn_clear1;
  private javax.swing.JButton btn_division;
  public javax.swing.JButton btn_igual;
  private javax.swing.JButton btn_producto;
  private javax.swing.JButton btn_punto;
  private javax.swing.JButton btn_resta;
  private javax.swing.JButton btn_suma;
  public javax.swing.JCheckBox chb_conversiones;
  public javax.swing.JCheckBox chb_operaciones;
  public javax.swing.JMenuItem item_basica;
  public javax.swing.JMenuItem item_estadistica;
  public javax.swing.JMenuItem item_salir;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  public javax.swing.JMenu m_vistas;
  private javax.swing.JMenuBar mbar;
  private javax.swing.JPanel pn_booleno;
  public javax.swing.JRadioButton rbtn_binario;
  public javax.swing.JRadioButton rbtn_binario1;
  public javax.swing.JRadioButton rbtn_decimal;
  public javax.swing.JRadioButton rbtn_decimal1;
  public javax.swing.JRadioButton rbtn_hexad;
  public javax.swing.JRadioButton rbtn_hexad1;
  public javax.swing.JRadioButton rbtn_octal;
  public javax.swing.JRadioButton rbtn_octal1;
  public javax.swing.JTextField txt_result;
  // End of variables declaration//GEN-END:variables
}
