/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ventana.java
 *
 * Created on 26-jun-2012, 14:23:16
 */
package vista;

/**
 *
 * @author izerowhitehat
 */
public class Ventana extends javax.swing.JFrame {
    
    /** Creates new form Ventana */
    public Ventana() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lbl_capital1 = new javax.swing.JLabel();
        lbl_interes1 = new javax.swing.JLabel();
        lbl_tiempo1 = new javax.swing.JLabel();
        txt_capital1 = new javax.swing.JTextField();
        txt_interes1 = new javax.swing.JTextField();
        txt_tiempo1 = new javax.swing.JTextField();
        btn_interesT2 = new javax.swing.JButton();
        txt_interesT2 = new javax.swing.JTextField();
        jcb_tiempo1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_interesT3 = new javax.swing.JTextField();
        btn_interesT3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbl_capital2 = new javax.swing.JLabel();
        lbl_interes2 = new javax.swing.JLabel();
        lbl_tiempo2 = new javax.swing.JLabel();
        txt_capital2 = new javax.swing.JTextField();
        txt_interes2 = new javax.swing.JTextField();
        txt_tiempo2 = new javax.swing.JTextField();
        btn_interesT4 = new javax.swing.JButton();
        txt_interesT4 = new javax.swing.JTextField();
        jcb_tiempo2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_interesT5 = new javax.swing.JTextField();
        btn_interesT5 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_resultado = new javax.swing.JTextField();
        btn_memoria = new javax.swing.JButton();
        btn_listaMemoria = new javax.swing.JButton();
        btn_fix = new javax.swing.JButton();
        btn_file = new javax.swing.JButton();
        txt_fix = new javax.swing.JTextField();
        txt_anuncio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_sin = new javax.swing.JButton();
        btn_cos = new javax.swing.JButton();
        btn_tan = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();
        btn_raiz = new javax.swing.JButton();
        btn_asin = new javax.swing.JButton();
        btn_acos = new javax.swing.JButton();
        btn_atan = new javax.swing.JButton();
        btn_ln = new javax.swing.JButton();
        btn_pot = new javax.swing.JButton();
        btn_siete = new javax.swing.JButton();
        btn_ocho = new javax.swing.JButton();
        btn_nueve = new javax.swing.JButton();
        btn_parenIzq = new javax.swing.JButton();
        btn_parenDer = new javax.swing.JButton();
        btn_cuatro = new javax.swing.JButton();
        btn_cinco = new javax.swing.JButton();
        btn_seis = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_dos = new javax.swing.JButton();
        btn_tres = new javax.swing.JButton();
        btn_uno = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_exponente = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_cero = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        pn_finanza = new javax.swing.JPanel();
        lbl_capInicial = new javax.swing.JLabel();
        txt_capInicial = new javax.swing.JTextField();
        lbl_Interes = new javax.swing.JLabel();
        txt_interes = new javax.swing.JTextField();
        lbl_tiempo = new javax.swing.JLabel();
        txt_tiempo = new javax.swing.JTextField();
        jcb_tiempo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        btn_totalS = new javax.swing.JButton();
        txt_totalS = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btn_totalC = new javax.swing.JButton();
        txt_totalC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pn_booleno = new javax.swing.JPanel();
        txt_decBase = new javax.swing.JTextField();
        btn_decBase = new javax.swing.JButton();
        jcb_bases = new javax.swing.JComboBox();
        txt_baseDec = new javax.swing.JTextField();
        btn_baseDec = new javax.swing.JButton();
        jcb_baseDec = new javax.swing.JComboBox();
        txt_opBases = new javax.swing.JTextField();
        btn_opBases = new javax.swing.JButton();
        lbl_decBase = new javax.swing.JLabel();
        lbl_baseDec = new javax.swing.JLabel();
        lbl_sumaAmbos = new javax.swing.JLabel();
        jcb_opBases = new javax.swing.JComboBox();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Finanzas"));

        lbl_capital1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lbl_capital1.setText("Capital Inicial");

        lbl_interes1.setText("Tasa de Interes");

        lbl_tiempo1.setText("Tiempo");

        txt_capital1.setText("jTextField2");

        txt_interes1.setText("jTextField3");

        txt_tiempo1.setText("jTextField4");

        btn_interesT2.setText("Interes Total");

        txt_interesT2.setText("jTextField4");

        jcb_tiempo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("jLabel1");

        jLabel4.setText("jLabel1");

        txt_interesT3.setText("jTextField4");

        btn_interesT3.setText("Interes Total");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_interes1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_capital1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(txt_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcb_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(125, 125, 125))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lbl_tiempo1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lbl_interes1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lbl_capital1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_interesT3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_interesT3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_interesT2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_interesT2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_capital1)
                .addGap(18, 18, 18)
                .addComponent(txt_capital1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lbl_interes1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_interes1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbl_tiempo1)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_interesT2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_interesT2))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_interesT3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_interesT3))
                .addGap(31, 31, 31))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Finanzas"));

        lbl_capital2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lbl_capital2.setText("Capital Inicial");

        lbl_interes2.setText("Tasa de Interes");

        lbl_tiempo2.setText("Tiempo");

        txt_capital2.setText("jTextField2");

        txt_interes2.setText("jTextField3");

        txt_tiempo2.setText("jTextField4");

        btn_interesT4.setText("Interes Total");

        txt_interesT4.setText("jTextField4");

        jcb_tiempo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("jLabel1");

        jLabel6.setText("jLabel1");

        txt_interesT5.setText("jTextField4");

        btn_interesT5.setText("Interes Total");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_interes2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_capital2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(txt_tiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcb_tiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(125, 125, 125))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lbl_tiempo2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lbl_interes2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lbl_capital2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_interesT5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_interesT5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_interesT4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_interesT4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_capital2)
                .addGap(18, 18, 18)
                .addComponent(txt_capital2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lbl_interes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_interes2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbl_tiempo2)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_tiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tiempo2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_interesT4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_interesT4))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_interesT5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_interesT5))
                .addGap(31, 31, 31))
        );

        jTextField8.setText("jTextField4");

        jButton5.setText(">");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));

        txt_resultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_resultadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_resultadoKeyReleased(evt);
            }
        });

        btn_memoria.setText("M");

        btn_listaMemoria.setText("LM");
        btn_listaMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaMemoriaActionPerformed(evt);
            }
        });

        btn_fix.setText("FIX");

        btn_file.setText("FILE");
        btn_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fileActionPerformed(evt);
            }
        });

        txt_fix.setEditable(false);
        txt_fix.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_listaMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fix, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fix, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_file, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_anuncio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_resultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                        .addGap(13, 13, 13))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_anuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txt_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_memoria)
                    .addComponent(txt_fix, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_fix)
                    .addComponent(btn_listaMemoria)
                    .addComponent(btn_file))
                .addContainerGap())
        );

        btn_sin.setBackground(new java.awt.Color(204, 204, 0));
        btn_sin.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        btn_sin.setText("SIN");
        btn_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sinActionPerformed(evt);
            }
        });

        btn_cos.setBackground(new java.awt.Color(204, 204, 0));
        btn_cos.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        btn_cos.setText("COS");
        btn_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cosActionPerformed(evt);
            }
        });

        btn_tan.setBackground(new java.awt.Color(204, 204, 0));
        btn_tan.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        btn_tan.setText("TAN");
        btn_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tanActionPerformed(evt);
            }
        });

        btn_log.setBackground(new java.awt.Color(204, 204, 0));
        btn_log.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        btn_log.setText("LOG");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        btn_raiz.setBackground(new java.awt.Color(204, 204, 0));
        btn_raiz.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        btn_raiz.setText("√");
        btn_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raizActionPerformed(evt);
            }
        });

        btn_asin.setBackground(new java.awt.Color(204, 204, 0));
        btn_asin.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        btn_asin.setText("ASIN");
        btn_asin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asinActionPerformed(evt);
            }
        });

        btn_acos.setBackground(new java.awt.Color(204, 204, 0));
        btn_acos.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        btn_acos.setText("ACOS");
        btn_acos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acosActionPerformed(evt);
            }
        });

        btn_atan.setBackground(new java.awt.Color(204, 204, 0));
        btn_atan.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        btn_atan.setText("ATAN");
        btn_atan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atanActionPerformed(evt);
            }
        });

        btn_ln.setBackground(new java.awt.Color(204, 204, 0));
        btn_ln.setFont(new java.awt.Font("Monospaced", 1, 9)); // NOI18N
        btn_ln.setText("LN");
        btn_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lnActionPerformed(evt);
            }
        });

        btn_pot.setBackground(new java.awt.Color(204, 204, 0));
        btn_pot.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_pot.setText("^");
        btn_pot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_potActionPerformed(evt);
            }
        });

        btn_siete.setBackground(new java.awt.Color(255, 255, 204));
        btn_siete.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_siete.setText("7");
        btn_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sieteActionPerformed(evt);
            }
        });

        btn_ocho.setBackground(new java.awt.Color(255, 255, 204));
        btn_ocho.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_ocho.setText("8");
        btn_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ochoActionPerformed(evt);
            }
        });

        btn_nueve.setBackground(new java.awt.Color(255, 255, 204));
        btn_nueve.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_nueve.setText("9");
        btn_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nueveActionPerformed(evt);
            }
        });

        btn_parenIzq.setBackground(new java.awt.Color(204, 255, 255));
        btn_parenIzq.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_parenIzq.setText("(");
        btn_parenIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parenIzqActionPerformed(evt);
            }
        });

        btn_parenDer.setBackground(new java.awt.Color(204, 255, 255));
        btn_parenDer.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_parenDer.setText(")");
        btn_parenDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parenDerActionPerformed(evt);
            }
        });

        btn_cuatro.setBackground(new java.awt.Color(255, 255, 204));
        btn_cuatro.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_cuatro.setText("4");
        btn_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuatroActionPerformed(evt);
            }
        });

        btn_cinco.setBackground(new java.awt.Color(255, 255, 204));
        btn_cinco.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_cinco.setText("5");
        btn_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cincoActionPerformed(evt);
            }
        });

        btn_seis.setBackground(new java.awt.Color(255, 255, 204));
        btn_seis.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_seis.setText("6");
        btn_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seisActionPerformed(evt);
            }
        });

        btn_multiplicar.setBackground(new java.awt.Color(0, 153, 255));
        btn_multiplicar.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_multiplicar.setText("*");
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });

        btn_division.setBackground(new java.awt.Color(0, 153, 255));
        btn_division.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_division.setText("/");
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });

        btn_dos.setBackground(new java.awt.Color(255, 255, 204));
        btn_dos.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_dos.setText("2");
        btn_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dosActionPerformed(evt);
            }
        });

        btn_tres.setBackground(new java.awt.Color(255, 255, 204));
        btn_tres.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_tres.setText("3");
        btn_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tresActionPerformed(evt);
            }
        });

        btn_uno.setBackground(new java.awt.Color(255, 255, 204));
        btn_uno.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_uno.setText("1");
        btn_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_unoActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(255, 0, 0));
        btn_igual.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_igual.setText("=");

        btn_clear.setBackground(new java.awt.Color(255, 153, 51));
        btn_clear.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_clear.setText("AC");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_exponente.setBackground(new java.awt.Color(255, 255, 204));
        btn_exponente.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_exponente.setText("E");
        btn_exponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exponenteActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(255, 255, 204));
        btn_punto.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_punto.setText(".");
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_cero.setBackground(new java.awt.Color(255, 255, 204));
        btn_cero.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_cero.setText("0");
        btn_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceroActionPerformed(evt);
            }
        });

        btn_suma.setBackground(new java.awt.Color(0, 153, 255));
        btn_suma.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_suma.setText("+");
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_resta.setBackground(new java.awt.Color(0, 153, 255));
        btn_resta.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btn_resta.setText("-");
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_cero, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(btn_uno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_dos, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(btn_punto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_exponente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(btn_suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_resta, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(btn_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_siete, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_seis, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(btn_nueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_multiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(btn_parenIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_parenDer, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(btn_division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_asin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_acos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_atan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_raiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_pot, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sin)
                    .addComponent(btn_cos)
                    .addComponent(btn_log)
                    .addComponent(btn_raiz)
                    .addComponent(btn_tan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_asin)
                        .addComponent(btn_acos)
                        .addComponent(btn_atan)
                        .addComponent(btn_ln)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_siete)
                    .addComponent(btn_ocho)
                    .addComponent(btn_nueve)
                    .addComponent(btn_parenIzq)
                    .addComponent(btn_parenDer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cuatro)
                    .addComponent(btn_cinco)
                    .addComponent(btn_seis)
                    .addComponent(btn_multiplicar)
                    .addComponent(btn_division))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_uno)
                    .addComponent(btn_dos)
                    .addComponent(btn_tres)
                    .addComponent(btn_suma)
                    .addComponent(btn_resta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cero)
                    .addComponent(btn_punto)
                    .addComponent(btn_exponente)
                    .addComponent(btn_clear)
                    .addComponent(btn_igual))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn_finanza.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Financiera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Unicode MS", 1, 14))); // NOI18N

        lbl_capInicial.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_capInicial.setText("Capital Inicial");

        lbl_Interes.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_Interes.setText("Tasa de Interes");

        lbl_tiempo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_tiempo.setText("Tiempo");

        jcb_tiempo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dias", "meses", "trimestres", "semestres", "años" }));

        btn_totalS.setText("Interes Simple");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_totalS, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_totalS, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btn_totalS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_totalS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btn_totalC.setText("Interes Compuesto");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_totalC, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_totalC)
                        .addGap(24, 24, 24))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btn_totalC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txt_totalC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("%");

        javax.swing.GroupLayout pn_finanzaLayout = new javax.swing.GroupLayout(pn_finanza);
        pn_finanza.setLayout(pn_finanzaLayout);
        pn_finanzaLayout.setHorizontalGroup(
            pn_finanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_finanzaLayout.createSequentialGroup()
                .addGroup(pn_finanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_finanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_finanzaLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(pn_finanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Interes)
                                .addGroup(pn_finanzaLayout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(lbl_tiempo))
                                .addGroup(pn_finanzaLayout.createSequentialGroup()
                                    .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcb_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pn_finanzaLayout.createSequentialGroup()
                                    .addGroup(pn_finanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_interes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                        .addComponent(txt_capInicial, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1)))))
                    .addGroup(pn_finanzaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lbl_capInicial))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_finanzaLayout.setVerticalGroup(
            pn_finanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_finanzaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_capInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_capInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_Interes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_finanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_tiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_finanzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        pn_booleno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booleanos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Unicode MS", 1, 14), java.awt.Color.darkGray)); // NOI18N

        btn_decBase.setText(">");

        jcb_bases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Binario", "Octal", "Hexadecimal" }));
        jcb_bases.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_baseDec.setText(">");

        jcb_baseDec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Binario", "Octal", "Hexadecimal" }));
        jcb_baseDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_baseDecActionPerformed(evt);
            }
        });

        btn_opBases.setText(">");

        lbl_decBase.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_decBase.setText("Decimal a Base");

        lbl_baseDec.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_baseDec.setText("Base a Decimal");

        lbl_sumaAmbos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_sumaAmbos.setText("Ambos");

        jcb_opBases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sumar", "restar" }));

        javax.swing.GroupLayout pn_boolenoLayout = new javax.swing.GroupLayout(pn_booleno);
        pn_booleno.setLayout(pn_boolenoLayout);
        pn_boolenoLayout.setHorizontalGroup(
            pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_boolenoLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lbl_decBase)
                .addGap(46, 46, 46))
            .addGroup(pn_boolenoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pn_boolenoLayout.createSequentialGroup()
                            .addComponent(btn_baseDec)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_baseDec))
                        .addGroup(pn_boolenoLayout.createSequentialGroup()
                            .addComponent(btn_decBase)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_baseDec)
                                .addComponent(txt_decBase)))
                        .addComponent(jcb_bases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcb_baseDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_boolenoLayout.createSequentialGroup()
                        .addComponent(jcb_opBases, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_sumaAmbos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_boolenoLayout.createSequentialGroup()
                        .addComponent(btn_opBases)
                        .addGap(18, 18, 18)
                        .addComponent(txt_opBases, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pn_boolenoLayout.setVerticalGroup(
            pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_boolenoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_decBase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_bases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_decBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_decBase))
                .addGap(53, 53, 53)
                .addComponent(lbl_baseDec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_baseDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_baseDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_baseDec))
                .addGap(30, 30, 30)
                .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_opBases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sumaAmbos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_boolenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_opBases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_opBases))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_booleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_finanza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pn_finanza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(pn_booleno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seisActionPerformed
// TODO add your handling code here:
    parseBotones("6");
}//GEN-LAST:event_btn_seisActionPerformed

private void btn_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sinActionPerformed
// TODO add your handling code here:
    parseBotones("sin");
}//GEN-LAST:event_btn_sinActionPerformed

private void btn_asinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asinActionPerformed
// TODO add your handling code here:
    parseBotones("asin");
}//GEN-LAST:event_btn_asinActionPerformed

private void btn_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceroActionPerformed
// TODO add your handling code here:
    parseBotones("0");
//    txt_resultado.setText(INPUT);
}//GEN-LAST:event_btn_ceroActionPerformed

private void btn_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unoActionPerformed
// TODO add your handling code here:
    parseBotones("1");
}//GEN-LAST:event_btn_unoActionPerformed

private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
// TODO add your handling code here:
    parseBotones(".");
}//GEN-LAST:event_btn_puntoActionPerformed

private void btn_exponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exponenteActionPerformed
// TODO add your handling code here:
    parseBotones("E");
}//GEN-LAST:event_btn_exponenteActionPerformed

private void btn_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dosActionPerformed
// TODO add your handling code here:
    parseBotones("2");
}//GEN-LAST:event_btn_dosActionPerformed

private void btn_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tresActionPerformed
// TODO add your handling code here:
    parseBotones("3");
}//GEN-LAST:event_btn_tresActionPerformed

private void btn_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuatroActionPerformed
// TODO add your handling code here:
    parseBotones("4");
}//GEN-LAST:event_btn_cuatroActionPerformed

private void btn_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cincoActionPerformed
// TODO add your handling code here:
    parseBotones("5");
}//GEN-LAST:event_btn_cincoActionPerformed

private void btn_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sieteActionPerformed
// TODO add your handling code here:
    parseBotones("7");
}//GEN-LAST:event_btn_sieteActionPerformed

private void btn_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ochoActionPerformed
// TODO add your handling code here:
    parseBotones("8");
}//GEN-LAST:event_btn_ochoActionPerformed

private void btn_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueveActionPerformed
// TODO add your handling code here:
    parseBotones("9");
}//GEN-LAST:event_btn_nueveActionPerformed

private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
// TODO add your handling code here:
    parseBotones("+");
}//GEN-LAST:event_btn_sumaActionPerformed

private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
// TODO add your handling code here:
    parseBotones("-");
}//GEN-LAST:event_btn_restaActionPerformed

private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
// TODO add your handling code here:
    parseBotones("*");
}//GEN-LAST:event_btn_multiplicarActionPerformed

private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
// TODO add your handling code here:
    parseBotones("/");
}//GEN-LAST:event_btn_divisionActionPerformed

private void btn_parenIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parenIzqActionPerformed
// TODO add your handling code here:
    parseBotones("(");
}//GEN-LAST:event_btn_parenIzqActionPerformed

private void btn_parenDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parenDerActionPerformed
// TODO add your handling code here:
    parseBotones(")");
}//GEN-LAST:event_btn_parenDerActionPerformed

private void btn_potActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_potActionPerformed
// TODO add your handling code here:
    parseBotones("^");
}//GEN-LAST:event_btn_potActionPerformed

private void btn_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lnActionPerformed
// TODO add your handling code here:
    parseBotones("ln");
}//GEN-LAST:event_btn_lnActionPerformed

private void btn_atanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atanActionPerformed
// TODO add your handling code here:
    parseBotones("atan");
}//GEN-LAST:event_btn_atanActionPerformed

private void btn_acosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acosActionPerformed
// TODO add your handling code here:
    parseBotones("acos");
}//GEN-LAST:event_btn_acosActionPerformed

private void btn_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cosActionPerformed
// TODO add your handling code here:
    parseBotones("cos");
}//GEN-LAST:event_btn_cosActionPerformed

private void btn_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tanActionPerformed
// TODO add your handling code here:
    parseBotones("tan");
}//GEN-LAST:event_btn_tanActionPerformed

private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
// TODO add your handling code here:
    parseBotones("log");
}//GEN-LAST:event_btn_logActionPerformed

private void btn_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raizActionPerformed
// TODO add your handling code here:
    parseBotones("√");
}//GEN-LAST:event_btn_raizActionPerformed

private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
// TODO add your handling code here:
  txt_resultado.setText("");
}//GEN-LAST:event_btn_clearActionPerformed

private void txt_resultadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_resultadoKeyPressed
// TODO add your handling code here:
  /*
  if(evt.getKeyCode()== KeyEvent.VK_ENTER){
    band=0;
    Calc cal=new Calc();
    String aux=txt_resultado.getText();
    if(validar(aux)){
      String aux1=aux;
      txt_anuncio.setText(aux1);
      addMemoria(aux);
      String resultado=cal.calBasica(aux, 0);
      aux=resultado;
      txt_resultado.setText(aux);
    }
  }*/
  
    
}//GEN-LAST:event_txt_resultadoKeyPressed

  private void txt_resultadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_resultadoKeyReleased
    // TODO add your handling code here:
    
  }//GEN-LAST:event_txt_resultadoKeyReleased

  private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jComboBox7ActionPerformed

  private void jcb_baseDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_baseDecActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jcb_baseDecActionPerformed

  private void btn_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fileActionPerformed
    // TODO add your handling code here:
    
  }//GEN-LAST:event_btn_fileActionPerformed

  private void btn_listaMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaMemoriaActionPerformed
    // TODO add your handling code here:
    Dlg_info dlg_info=new Dlg_info(this, rootPaneCheckingEnabled);
    dlg_info.txtA_info.setText("Hola como estas");
    dlg_info.setVisible(rootPaneCheckingEnabled);
  }//GEN-LAST:event_btn_listaMemoriaActionPerformed
    
  
  
  
  
private void parseBotones(String boton){
  if(txt_resultado.getText().equals("") ){
    txt_resultado.setText(boton);
    String aux=txt_resultado.getText();
    txt_resultado.setText(aux);
  }else{
    String aux=txt_resultado.getText()+boton;
    txt_resultado.setText(aux);
  }
}

  

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acos;
    private javax.swing.JButton btn_asin;
    private javax.swing.JButton btn_atan;
    public javax.swing.JButton btn_baseDec;
    private javax.swing.JButton btn_cero;
    private javax.swing.JButton btn_cinco;
    public javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_cos;
    private javax.swing.JButton btn_cuatro;
    public javax.swing.JButton btn_decBase;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_dos;
    private javax.swing.JButton btn_exponente;
    private javax.swing.JButton btn_file;
    public javax.swing.JButton btn_fix;
    public javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_interesT2;
    private javax.swing.JButton btn_interesT3;
    private javax.swing.JButton btn_interesT4;
    private javax.swing.JButton btn_interesT5;
    private javax.swing.JButton btn_listaMemoria;
    private javax.swing.JButton btn_ln;
    private javax.swing.JButton btn_log;
    public javax.swing.JButton btn_memoria;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_nueve;
    private javax.swing.JButton btn_ocho;
    public javax.swing.JButton btn_opBases;
    private javax.swing.JButton btn_parenDer;
    private javax.swing.JButton btn_parenIzq;
    private javax.swing.JButton btn_pot;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_raiz;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_seis;
    private javax.swing.JButton btn_siete;
    private javax.swing.JButton btn_sin;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton btn_tan;
    public javax.swing.JButton btn_totalC;
    public javax.swing.JButton btn_totalS;
    private javax.swing.JButton btn_tres;
    private javax.swing.JButton btn_uno;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField8;
    public javax.swing.JComboBox jcb_baseDec;
    public javax.swing.JComboBox jcb_bases;
    public javax.swing.JComboBox jcb_opBases;
    public javax.swing.JComboBox jcb_tiempo;
    private javax.swing.JComboBox jcb_tiempo1;
    private javax.swing.JComboBox jcb_tiempo2;
    private javax.swing.JLabel lbl_Interes;
    private javax.swing.JLabel lbl_baseDec;
    private javax.swing.JLabel lbl_capInicial;
    private javax.swing.JLabel lbl_capital1;
    private javax.swing.JLabel lbl_capital2;
    private javax.swing.JLabel lbl_decBase;
    private javax.swing.JLabel lbl_interes1;
    private javax.swing.JLabel lbl_interes2;
    private javax.swing.JLabel lbl_sumaAmbos;
    private javax.swing.JLabel lbl_tiempo;
    private javax.swing.JLabel lbl_tiempo1;
    private javax.swing.JLabel lbl_tiempo2;
    private javax.swing.JPanel pn_booleno;
    private javax.swing.JPanel pn_finanza;
    public javax.swing.JTextField txt_anuncio;
    public javax.swing.JTextField txt_baseDec;
    public javax.swing.JTextField txt_capInicial;
    private javax.swing.JTextField txt_capital1;
    private javax.swing.JTextField txt_capital2;
    public javax.swing.JTextField txt_decBase;
    public javax.swing.JTextField txt_fix;
    public javax.swing.JTextField txt_interes;
    private javax.swing.JTextField txt_interes1;
    private javax.swing.JTextField txt_interes2;
    private javax.swing.JTextField txt_interesT2;
    private javax.swing.JTextField txt_interesT3;
    private javax.swing.JTextField txt_interesT4;
    private javax.swing.JTextField txt_interesT5;
    public javax.swing.JTextField txt_opBases;
    public javax.swing.JTextField txt_resultado;
    public javax.swing.JTextField txt_tiempo;
    private javax.swing.JTextField txt_tiempo1;
    private javax.swing.JTextField txt_tiempo2;
    public javax.swing.JTextField txt_totalC;
    public javax.swing.JTextField txt_totalS;
    // End of variables declaration//GEN-END:variables
}
