/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Administrador
 */
public class Vestadisca extends javax.swing.JFrame {

  /**
   * Creates new form Vestadisca
   */
  public Vestadisca() {
    initComponents();
    pn_interesComp.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLayeredPane1 = new javax.swing.JLayeredPane();
    pn_interesComp = new javax.swing.JPanel();
    lbl_capInicial1 = new javax.swing.JLabel();
    txt_capInicial1 = new javax.swing.JTextField();
    lbl_Interes1 = new javax.swing.JLabel();
    txt_interes1 = new javax.swing.JTextField();
    lbl_tiempo1 = new javax.swing.JLabel();
    txt_tiempo1 = new javax.swing.JTextField();
    jcb_tiempo1 = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    txt_totalC1 = new javax.swing.JTextField();
    btn_totalC1 = new javax.swing.JButton();
    pn_interesSimp = new javax.swing.JPanel();
    lbl_capInicial = new javax.swing.JLabel();
    txt_capInicial = new javax.swing.JTextField();
    lbl_Interes = new javax.swing.JLabel();
    txt_interes = new javax.swing.JTextField();
    lbl_tiempo = new javax.swing.JLabel();
    txt_tiempo = new javax.swing.JTextField();
    jcb_tiempo = new javax.swing.JComboBox();
    jLabel1 = new javax.swing.JLabel();
    txt_totalS = new javax.swing.JTextField();
    btn_totalS = new javax.swing.JButton();
    mbar = new javax.swing.JMenuBar();
    m_vistas = new javax.swing.JMenu();
    item_basica = new javax.swing.JMenuItem();
    item_booleana = new javax.swing.JMenuItem();
    item_salir = new javax.swing.JMenuItem();
    m_calculos = new javax.swing.JMenu();
    item_intSimple = new javax.swing.JMenuItem();
    item_intCompuesto = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    pn_interesComp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Interes compuesto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

    lbl_capInicial1.setFont(new java.awt.Font("Verdana", 1, 14));
    lbl_capInicial1.setText("Capital Inicial");

    lbl_Interes1.setFont(new java.awt.Font("Verdana", 1, 14));
    lbl_Interes1.setText("Tasa de Interes");

    lbl_tiempo1.setFont(new java.awt.Font("Verdana", 1, 14));
    lbl_tiempo1.setText("Tiempo");

    jcb_tiempo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dias", "meses", "trimestres", "semestres", "años" }));

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
    jLabel2.setText("%");

    btn_totalC1.setText("Interes Compuesto");

    javax.swing.GroupLayout pn_interesCompLayout = new javax.swing.GroupLayout(pn_interesComp);
    pn_interesComp.setLayout(pn_interesCompLayout);
    pn_interesCompLayout.setHorizontalGroup(
      pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_interesCompLayout.createSequentialGroup()
        .addGroup(pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pn_interesCompLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(txt_totalC1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(pn_interesCompLayout.createSequentialGroup()
                  .addGroup(pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Interes1)
                    .addComponent(lbl_capInicial1))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_interesCompLayout.createSequentialGroup()
                      .addComponent(txt_interes1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addGap(3, 3, 3)
                      .addComponent(jLabel2))
                    .addComponent(txt_capInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                .addGroup(pn_interesCompLayout.createSequentialGroup()
                  .addComponent(lbl_tiempo1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txt_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jcb_tiempo1, 0, 0, Short.MAX_VALUE)))))
          .addGroup(pn_interesCompLayout.createSequentialGroup()
            .addGap(56, 56, 56)
            .addComponent(btn_totalC1)))
        .addContainerGap(32, Short.MAX_VALUE))
    );
    pn_interesCompLayout.setVerticalGroup(
      pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_interesCompLayout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addGroup(pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txt_capInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbl_capInicial1))
        .addGap(18, 18, 18)
        .addGroup(pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(lbl_Interes1)
          .addGroup(pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(txt_interes1)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)))
        .addGap(18, 18, 18)
        .addGroup(pn_interesCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_tiempo1)
          .addComponent(txt_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jcb_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(53, 53, 53)
        .addComponent(btn_totalC1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txt_totalC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(104, Short.MAX_VALUE))
    );

    pn_interesCompLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_capInicial1, txt_interes1, txt_tiempo1});

    pn_interesComp.setBounds(7, 10, 300, 390);
    jLayeredPane1.add(pn_interesComp, javax.swing.JLayeredPane.DEFAULT_LAYER);

    pn_interesSimp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Interes Simple", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

    lbl_capInicial.setFont(new java.awt.Font("Verdana", 1, 14));
    lbl_capInicial.setText("Capital Inicial");

    lbl_Interes.setFont(new java.awt.Font("Verdana", 1, 14));
    lbl_Interes.setText("Tasa de Interes");

    lbl_tiempo.setFont(new java.awt.Font("Verdana", 1, 14));
    lbl_tiempo.setText("Tiempo");

    jcb_tiempo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dias", "meses", "trimestres", "semestres", "años" }));

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
    jLabel1.setText("%");

    btn_totalS.setText("Interes Simple");

    javax.swing.GroupLayout pn_interesSimpLayout = new javax.swing.GroupLayout(pn_interesSimp);
    pn_interesSimp.setLayout(pn_interesSimpLayout);
    pn_interesSimpLayout.setHorizontalGroup(
      pn_interesSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_interesSimpLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pn_interesSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_interesSimpLayout.createSequentialGroup()
            .addComponent(lbl_tiempo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jcb_tiempo, 0, 82, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_interesSimpLayout.createSequentialGroup()
            .addGroup(pn_interesSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lbl_Interes)
              .addComponent(lbl_capInicial))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pn_interesSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(pn_interesSimpLayout.createSequentialGroup()
                .addComponent(txt_interes, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(jLabel1))
              .addComponent(txt_capInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
          .addComponent(txt_totalS, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(39, 39, 39))
      .addGroup(pn_interesSimpLayout.createSequentialGroup()
        .addGap(60, 60, 60)
        .addComponent(btn_totalS, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(58, Short.MAX_VALUE))
    );
    pn_interesSimpLayout.setVerticalGroup(
      pn_interesSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pn_interesSimpLayout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addGroup(pn_interesSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txt_capInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbl_capInicial))
        .addGap(18, 18, 18)
        .addGroup(pn_interesSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(lbl_Interes)
          .addGroup(pn_interesSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(txt_interes)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)))
        .addGap(18, 18, 18)
        .addGroup(pn_interesSimpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_tiempo)
          .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jcb_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(50, 50, 50)
        .addComponent(btn_totalS)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txt_totalS, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        .addGap(121, 121, 121))
    );

    pn_interesSimpLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcb_tiempo, txt_capInicial, txt_interes, txt_tiempo});

    pn_interesSimp.setBounds(10, 10, 300, 390);
    jLayeredPane1.add(pn_interesSimp, javax.swing.JLayeredPane.DEFAULT_LAYER);

    m_vistas.setText("Vistas");

    item_basica.setText("basica");
    item_basica.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        item_basicaActionPerformed(evt);
      }
    });
    m_vistas.add(item_basica);

    item_booleana.setText("booleana");
    item_booleana.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        item_booleanaActionPerformed(evt);
      }
    });
    m_vistas.add(item_booleana);

    item_salir.setText("Salir");
    m_vistas.add(item_salir);

    mbar.add(m_vistas);

    m_calculos.setText("Calculos");

    item_intSimple.setText("Interes Simple");
    m_calculos.add(item_intSimple);

    item_intCompuesto.setText("Interes Compuesto");
    m_calculos.add(item_intCompuesto);

    mbar.add(m_calculos);

    setJMenuBar(mbar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(20, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  
  
  
  private void item_basicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_basicaActionPerformed
    // TODO add your handling code here:
    /*if (vEst == false) {
      vest.setVisible(true);
      this.setVisible(false);
      vEst = true;
    } else {
      vest.setVisible(false);
      this.setVisible(true);
      vEst = false;
    }*/
  }//GEN-LAST:event_item_basicaActionPerformed

  private void item_booleanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_booleanaActionPerformed
    // TODO add your handling code here:
    /*if (vBol == false) {
      vbol.setVisible(true);
      this.setVisible(false);
      vBol = true;
    } else {
      vbol.setVisible(false);
      this.setVisible(true);
      vBol = false;
    }*/
  }//GEN-LAST:event_item_booleanaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Vestadisca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Vestadisca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Vestadisca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Vestadisca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new Vestadisca().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btn_totalC1;
  public javax.swing.JButton btn_totalS;
  public javax.swing.JMenuItem item_basica;
  public javax.swing.JMenuItem item_booleana;
  public javax.swing.JMenuItem item_intCompuesto;
  public javax.swing.JMenuItem item_intSimple;
  public javax.swing.JMenuItem item_salir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLayeredPane jLayeredPane1;
  public javax.swing.JComboBox jcb_tiempo;
  public javax.swing.JComboBox jcb_tiempo1;
  private javax.swing.JLabel lbl_Interes;
  private javax.swing.JLabel lbl_Interes1;
  private javax.swing.JLabel lbl_capInicial;
  private javax.swing.JLabel lbl_capInicial1;
  private javax.swing.JLabel lbl_tiempo;
  private javax.swing.JLabel lbl_tiempo1;
  private javax.swing.JMenu m_calculos;
  public javax.swing.JMenu m_vistas;
  private javax.swing.JMenuBar mbar;
  public javax.swing.JPanel pn_interesComp;
  public javax.swing.JPanel pn_interesSimp;
  public javax.swing.JTextField txt_capInicial;
  public javax.swing.JTextField txt_capInicial1;
  public javax.swing.JTextField txt_interes;
  public javax.swing.JTextField txt_interes1;
  public javax.swing.JTextField txt_tiempo;
  public javax.swing.JTextField txt_tiempo1;
  public javax.swing.JTextField txt_totalC1;
  public javax.swing.JTextField txt_totalS;
  // End of variables declaration//GEN-END:variables
}
